# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # Use this to override the hardware-configuration.nix file
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Basics
  services.pulseaudio.enable = false;
  hardware.enableAllFirmware = true; 
  hardware.graphics.enable = true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Bootloader
  boot.kernelModules = [ "nvidia" "amdgpu"  ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 100;
  boot.loader.efi.canTouchEfiVariables = true;

  # X11 and Wayland
  services.xserver.videoDrivers = [ "nvidia" "amdgpu" ];

  # TODO: Try Next Reset
  # LUKS FullDiskEncryption
  # boot.initrd.luks.devices = {
  #   luksroot = {
  #       device = "/dev/disk/by-uuid/4265d4f9-7f7b-4ebf-a3b4-a3406c3c0955";
  #       allowDiscards = true;
  #       keyFileSize = 4096;
  #       # pinning to /dev/disk/by-id/usbkey works
  #       keyFile = "/dev/sdb";
  #   };
  # };

  # Root
  fileSystems."/" = { 
      device = "/dev/disk/by-uuid/4265d4f9-7f7b-4ebf-a3b4-a3406c3c0955";
      fsType = "ext4";
      neededForBoot = true;
      options = [ "noatime" "nodiratime" "discard" "defaults" "commit=60" "barrier=0" "data=writeback" ];
    };

  # Boot
  fileSystems."/boot" = { 
      device = "/dev/disk/by-uuid/6B74-DC9D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Swap
  swapDevices =
    [ 
      # kinda works but takes a lot to boot before systemd
      # { device = "/dev/disk/by-uuid/0319478f-63cc-4fde-9804-523687d223ee"; priority = 10; options = [ "x-systemd.device-timeout=1ms" ]; } # optional g14 laptop swap
      { device = "/dev/disk/by-uuid/c824afe8-bf19-4f7f-9876-5fcff8c93593"; priority = 00; } # nomad usb stick
    ];
}


