services:
  app:
    build:
      context: ${MONOLITO_DIR}
      dockerfile: ${ZION_NIXOS_DIR}/self/containers/monolito/Dockerfile
    container_name: zion-dk-monolito-app
    cpus: "14.4"
    mem_limit: 6g
    memswap_limit: 6g
    env_file:
      - ${MONOLITO_DIR}/.env.${APP_ENV_FILE:-sandbox}
      - ./env/${APP_ENV:-sand}.env
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
    volumes:
      - ${MONOLITO_DIR}/configuration:/go/app/configuration:ro
      - /var/run/docker.sock:/var/run/docker.sock
      # Canal de comunicação rápida host ↔ container
      - ${HOME}/.zion:/.zion:rw
    ports:
      - "4004:4004"
      - "2345:2345"
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    name: nixos_default
    external: true
