# ===================================================================
#                           PROGRAM ALIASES
# ===================================================================
$hyprutils = source ~/.config/hypr/hyprutils.sh &&

# Apps
$terminal          = alacritty
$fileManager       = nautilus -w
$menu              = rofi -show drun
$lock              = hyprlock
$obsidian          = obsidian
$chrome            = google-chrome-stable --disable-extensions --no-proxy-server --no-first-run --disable-sync
$vivaldi           = vivaldi
$cursor	           = cursor
# $zed               = ~/.local/zed.app/bin/zed
$zed               = zeditor
$yaak              = appimage-run ~/apps/yaak.AppImage
$colorPicker       = hyprpicker --autocopy --lowercase-hex


# System Tools
$displayManager    = nwg-displays
$networkManager    = nmtui
$audioManager      = alacritty -e wiremix
$emojiPicker       = rofimoji --skin-tone neutral --action copy

# Shortcuts
$settings          = $zed ~/projects/nixos
$workObsidian      = $obsidian "obsidian://open?vault=Work"
$personalObsidian  = $obsidian "obsidian://open?vault=books"

# Personal Webapps
$youtubeMusic      = $vivaldi --app=https://music.youtube.com
$monkeyType        = $vivaldi --app=https://monkeytype.com
$rainmaker         = $vivaldi --app=https://www.youtube.com/watch?v=1Xiwqm94T4k

# Work Webapps
$nixSearch         = $chrome --new-window https://search.nixos.org/
$gemini            = $chrome --app=https://gemini.google.com/
$claude            = $chrome --app=https://claude.ai/new
$claudio           = alacritty --working-directory ~/projects/estrategia/claudio -e make claude
$calendar          = $chrome --app=https://calendar.google.com
$chat              = $chrome --app=https://chat.google.com
$youtube           = $chrome --app=https://www.youtube.com
$jira              = $chrome --new-window https://estrategia.atlassian.net/jira/software/c/projects/FUK2/boards/323?quickFilter=1182
$yaak              = notify-send "abrindo yaaaaak" && ~/apps/yaak.AppImage

# ===================================================================
#                          APP KEYBINDS
# ===================================================================

# Quick Apps
bind = MOD3, Space,  exec, $menu
bind = MOD3, t,      exec, $terminal
bind = MOD3, c,      exec, $cursor
bind = MOD3, e,      exec, ghostty -e yazi
bind = MOD3, z,      exec, $zed
bind = MOD3, period, exec, $emojiPicker
bind = MOD3, a,      exec, $audioManager
bind = MOD3, y,      exec, $yaak

# others
bind = MOD3, b,     exec, $chrome
bind = MOD3, g,     exec, $gemini
bind = MOD3 ALT, g, exec, $claude

bind = MOD3, f,     exec, $claudio

# # Custom Vibecoded Shader
# bind = SUPER, f2, exec, hyprshade toggle ~/.config/hyprshade/shaders/crt.frag
# # Other shaders
# bind = SUPER, f3, exec, hyprshade toggle ~/.config/hyprshade/shaders/cathode.frag
# bind = SUPER, f4, exec, hyprshade toggle ~/.config/hyprshade/shaders/scanlines.glsl
# bind = SUPER, f5, exec, hyprshade toggle ~/.config/hyprshade/shaders/red.frag

# # Shaders Config
# debug:damage_tracking = on;
# debug:disable_logs = false;
