always_show_default = true
command = 'xdg-open'
engines_as_actions = false
history = true
history_when_empty = false
text_prefix = 'Search: '

[Config]
hide_from_providerlist = false
icon = 'applications-internet'
min_score = 20
name_pretty = ''

[[entries]]
default = true
icon = ''
name = 'Google'
prefix = ''
url = 'https://www.google.com/search?q=%TERM%'

[[entries]]
default = false
icon = ''
name = 'GitHub'
prefix = 'gh'
url = 'https://github.com/search?q=%TERM%&type=code'

[[entries]]
default = false
icon = ''
name = 'Stack Overflow'
prefix = 'so'
url = 'https://stackoverflow.com/search?q=%TERM%'
