[[entries]]
default = true
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[entries]]
name = "GitHub"
prefix = "gh"
url = "https://github.com/search?q=%TERM%&type=code"

[[entries]]
name = "Stack Overflow"
prefix = "so"
url = "https://stackoverflow.com/search?q=%TERM%"
