services:
  app:
    build:
      dockerfile: Dockerfile.debug
    cpus: "14.4"
    # ptrace is required for delve to work inside Docker
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
