services:
  app:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ${MONOLITO_DIR}:/go/app
      - leech-go-build-cache:/root/.cache/go-build
      - .air.toml:/etc/air.toml:ro
    healthcheck:
      disable: true

volumes:
  leech-go-build-cache:
    name: leech-go-build-cache
