services:
  app:
    build:
      dockerfile: ${VENNON_SERVICE_DIR}/Dockerfile.dev
    volumes:
      - ${MONOLITO_DIR}:/go/app
      - vennon-go-build-cache:/root/.cache/go-build
      - .air.toml:/etc/air.toml:ro
    healthcheck:
      disable: true

volumes:
  vennon-go-build-cache:
    name: vennon-go-build-cache
