root = "."
tmp_dir = "/tmp/air"

[build]
  cmd = "CGO_ENABLED=1 go build -mod=vendor -tags musl -o /tmp/air/server ./cmd/server/main.go"
  bin = "/tmp/air/server"
  include_ext = ["go"]
  exclude_dir = ["vendor", "testdata", ".git", "tmp"]
  delay = 2000
  kill_delay = "2s"
  stop_on_error = false

[log]
  time = true
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
