services:
  app:
    build:
      dockerfile: ${LEECH_NIXOS_DIR}/leech/docker/monolito/Dockerfile.dev
    volumes:
      - ${MONOLITO_DIR}:/go/app
      - leech-go-build-cache:/root/.cache/go-build
      - ${LEECH_NIXOS_DIR}/leech/docker/monolito/.air.toml:/etc/air.toml:ro
    healthcheck:
      disable: true

volumes:
  leech-go-build-cache:
    name: leech-go-build-cache
