# Reverse proxy: 80/443 -> 4004 (monolito/front)
# Levantado automaticamente com qualquer servico estrategia.

server {
    listen 80;
    server_name localhost;
    location / {
        proxy_pass http://127.0.0.1:4004;
        proxy_set_header Host $host;
    }
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:4004;
        proxy_set_header Host $host;
    }
}
